webtalk_init -webtalk_dir /home/vguittar/Bureau/4A/PSI/SystemeInformatique/PSI/PSI.sim/sim_1/behav/xsim/xsim.dir/testDATA_PATH_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 31 11:06:23 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "451c837147255741806fb852a5ffa071" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "803a732ea1e54d258d632fd6b12ac363" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114460_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3483134998 -regid "" -xml /home/vguittar/Bureau/4A/PSI/SystemeInformatique/PSI/PSI.sim/sim_1/behav/xsim/xsim.dir/testDATA_PATH_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/vguittar/Bureau/4A/PSI/SystemeInformatique/PSI/PSI.sim/sim_1/behav/xsim/xsim.dir/testDATA_PATH_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/vguittar/Bureau/4A/PSI/SystemeInformatique/PSI/PSI.sim/sim_1/behav/xsim/xsim.dir/testDATA_PATH_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
